// === KUMPULAN DATA PERTANYAAN (DATA NYS) ===
const FAQ_UMUM = [
    { q: 'Apa saja suku-suku yang ada di Papua berdasarkan data yang kamu punya?', a: 'Suku Asmat, Dani, Amungme, Kamoro, Biak, dan Sentani.' },
    { q: 'Suku mana di Papua yang paling terkenal dengan ukiran kayunya?', a: 'Suku Asmat.' },
    { q: 'Apa perbedaan Honai (Dani) dengan Jew (Asmat) atau Rumsram (Biak)?', a: 'Perbedaannya terletak pada bentuk, bahan, kapasitas, dan fungsi. Honai berbentuk bulat untuk 1 keluarga inti, Jew berbentuk panggung panjang untuk 10-12 KK dan ritual ukir, sedangkan Rumsram berbentuk perahu terbalik untuk 2-3 keluarga suku Biak.' },
    { q: 'Apakah semua suku di Papua memakai koteka?', a: 'Tidak semua. Laki-laki Asmat pakai kawat penis (labu kering), Dani dan Amungme pakai koteka, Kamoro pakai kawatka, Biak dan Sentani pakai cawat/sali dari kain/kulit kayu.' },
    { q: 'Makanan khas Papua yang paling umum di semua suku itu apa?', a: 'Papeda, sagu bakar, ulat sagu, ikan bakar, dan ubi jalar.' },
    { q: 'Apakah semua suku Papua punya tari perang?', a: 'Hampir semua, contoh: Tari Yamate (Asmat), Tari Perang (Dani), Tari Ehabla (Sentani), Tari War (Biak).' },
    { q: 'Apa nama festival budaya terbesar di Papua dari data tersebut?', a: 'Festival Lembah Baliem (Dani), Festival Asmat, Festival Danau Sentani, dan Festival Pesisir Biak.' },
    { q: 'Apakah ada suku di Papua yang tinggal di atas air atau danau?', a: 'Suku Sentani (Khouw di atas Danau Sentani) dan sebagian suku Kamoro di pesisir.' },
    { q: 'Suku mana yang punya rumah adat berbentuk perahu terbalik?', a: 'Suku Biak dengan Rumsram.' },
    { q: 'Apa itu noken dan suku mana saja yang menggunakannya?', a: 'Noken adalah tas anyaman dari serat atau kulit kayu, digunakan oleh perempuan Dani, Amungme, Kamoro, Sentani, dan lainnya.' },
    { q: 'Suku mana yang terkenal dengan tato di tubuh perempuannya?', a: 'Suku Kamoro, yang terkenal dengan tato motif lingkaran dan garis.' },
    { q: 'Apakah ada suku di Papua yang menggunakan alat musik dari keong laut?', a: 'Suku Asmat (Embra) dan Suku Kamoro (Okobere).' },
    { q: 'Wisata budaya suku mana yang paling mudah dijangkau wisatawan?', a: 'Secara relatif, Lembah Baliem (Dani) via Wamena, Danau Sentani via Jayapura, dan Pulau Biak lebih mudah dijangkau. Agats (Asmat) juga bisa dikunjungi tapi aksesnya lebih terbatas.' },
    { q: 'Apa perbedaan utama antara suku pegunungan (Dani, Amungme) dan suku pesisir (Asmat, Kamoro, Biak)?', a: 'Perbedaan utamanya ada pada rumah adat (Honai/Humai vs Jew/Komea/Rumsram), pakaian (koteka vs kawat penis/cawat), makanan pokok (ubi jalar dominan di pegunungan vs sagu di pesisir), dan jenis tarian.' },
    { q: 'Apakah semua suku di data Anda masih mempertahankan budaya asli hingga sekarang?', a: 'Masih, namun dengan tingkat yang berbeda-beda; festival dan upacara adat masih rutin digelar hingga saat ini.' }
];

const PERTANYAAN_SUKU_DATASET = {
    asmat: {
        rumah_adat: ['Rumah adat suku Asmat namanya apa? Apa itu rumah Jew?', 'Bentuk rumah Jew seperti apa? Apakah panggung?', 'Berapa lama rumah Jew bisa bertahan? Ada yang bilang 15–20 tahun?', 'Rumah Jew bisa dihuni berapa keluarga? 10 sampai 12 KK?', 'Fungsi rumah adat Asmat selain tempat tinggal apa? Buat upacara ukir ya?'],
        pakaian_laki_laki: ['Pakaian adat pria Asmat itu pakai kawat penis dari labu kering, benar?', 'Rok laki-laki Asmat terbuat dari serat sagu atau daun sagu?', 'Hiasan kepala suku Asmat pakai bulu burung apa? Bulu kasuari?', 'Aksesoris yang dipakai pria Asmat selain kawat penis ada taring babi, iya kan?', 'Bahan rok pria Asmat dari apa ya? Serat sagu?'],
        pakaian_perempuan: ['Pakaian adat wanita Asmat itu rok rumbai dari serat sagu, betul?', 'Perempuan Asmat melumuri tubuh dengan tanah liat atau minyak kelapa?', 'Kalung wanita Asmat dari gigi anjing atau kerang laut?', 'Rok perempuan Asmat panjang atau pendek?', 'Apa bedanya pakaian perempuan Asmat dengan suku Dani?'],
        makanan: ['Makanan khas suku Asmat apa aja? Ada sagu bakar dan papeda?', 'Ulat sagu panggang itu makanan ritual suku Asmat atau sehari-hari?', 'Ikan bakar termasuk makanan suku Asmat tidak?', 'Bubur sagu dengan kelapa itu makanan apa namanya?', 'Apa makanan pokok suku Asmat selain sagu?'],
        tarian: ['Tari perang suku Asmat namanya Tari Yamate, iya?', 'Tari Gantar itu tari gembira atau sedih?', 'Tari Bis untuk ritual roh leluhur, ceritanya gimana?', 'Apa saja tarian tradisional dari Asmat yang terkenal?', 'Kapan biasanya Tari Bis ditampilkan?'],
        hari_besar: ['Upacara atau hari besar suku Asmat apa saja?', 'Festival Pisau itu upacara ukir kayu ya?', 'Festival Asmat diselenggarakan bulan apa? Agustus?', 'Upacara Mbitoro itu untuk inisiasi laki-laki, benar?', 'Apa tujuan dari Festival Pisau?'],
        alat_musik: ['Alat musik tradisional suku Asmat apa? Ada tifa dari kayu sagu?', 'Fu itu suling bambu, bukan?', 'Embra terompet dari keong laut, bunyinya seperti apa?', 'Perbedaan tifa Asmat dengan tifa Biak apa?', 'Apa alat musik yang dipakai mengiringi Tari Bis?']
    },
    dani: {
        rumah_adat: ['Rumah adat suku Dani buat laki-laki namanya Honai, betul?', 'Kalau untuk perempuan, rumahnya disebut Ebeai, iya?', 'Honai bentuknya bulat atau kerucut? Dari bahan kayu dan jerami?', 'Berapa lama Honai bisa bertahan? 10–15 tahun?', 'Honai dihuni berapa orang? Satu keluarga inti?'],
        pakaian_laki_laki: ['Pakaian adat pria Dani yang paling khas itu koteka dari labu panjang, kan?', 'Aksesoris kepala suku Dani pakai bulu cenderawasih, benar?', 'Gelang pria Dani dari kulit kerang, ya?', 'Apa fungsi koteka selain penutup kemaluan?', 'Koteka suku Dani beda dengan koteka suku Amungme?'],
        pakaian_perempuan: ['Rok perempuan Dani dari serat tanaman atau daun?', 'Perempuan Dani melumuri tubuh dengan lemak babi dan tanah liat, iya?', 'Noken itu tas anyaman yang dipakai di punggung, bukan?', 'Apa bahan rok pendek wanita Dani?', 'Apakah perempuan Dani juga memakai koteka? Tidak, kan?'],
        makanan: ['Makanan khas suku Dani apa? Ubi jalar panggang batu?', 'Babi bakar itu makanan utama dalam upacara adat Dani?', 'Sayur keladi dan papeda sagu juga dimakan suku Dani?', 'Apa itu petatas? Sama dengan ubi jalar?', 'Ulat sagu juga jadi makanan suku Dani?'],
        tarian: ['Tari Perang suku Dani itu menirukan gerakan perang, ya?', 'Tari Gemabak untuk menyambut tamu, betul?', 'Tari Edlagan itu tari gembira, gerakannya gimana?', 'Apa nama tarian khas Dani yang sering di Festival Lembah Baliem?', 'Kapan Tari Perang biasanya ditampilkan?'],
        hari_besar: ['Festival Lembah Baliem diadakan bulan Agustus, iya?', 'Upacara Wamena itu bakar batu massal, benar?', 'Upacara Sumpah Babi untuk perdamaian antar suku?', 'Apa saja rangkaian Festival Lembah Baliem?', 'Apakah suku Dani juga merayakan pesta panen?'],
        alat_musik: ['Alat musik unik suku Dani namanya Pikon, dari getaran bambu?', 'Tifa kayu juga dipakai suku Dani?', 'Fu suling bambu, dan Kererut alat musik gesek dari bambu?', 'Apa beda Pikon dengan tifa?', 'Bagaimana cara memainkan Kererut?']
    },
    amungme: {
        rumah_adat: ['Rumah adat suku Amungme namanya Humai, bentuknya bulat seperti Honai?', 'Humai lebih kecil dari Honai, hanya untuk 1 KK, benar?', 'Bahan Humai dari kayu dan alang-alang, tahan 10 tahun?', 'Fungsi Humai selain tempat tinggal juga sebagai lumbung?', 'Apa perbedaan Humai dengan Ebeai milik suku Dani?'],
        pakaian_laki_laki: ['Pria Amungme memakai koteka pendek dari labu atau kayu?', 'Topi pria Amungme dari bulu burung, burung apa?', 'Kalung dari tulang hewan, biasanya tulang apa?', 'Apakah koteka Amungme lebih pendek dari koteka Dani?', 'Aksesoris lain yang dipakai pria Amungme?'],
        pakaian_perempuan: ['Rok perempuan Amungme dari daun atau serat?', 'Noken tas punggung juga dipakai wanita Amungme?', 'Penutup dada dari anyaman serat, bentuknya gimana?', 'Tubuh dihias dengan tanah liat merah, iya?', 'Apakah perempuan Amungme bertato seperti suku Kamoro?'],
        makanan: ['Makanan pokok suku Amungme ubi jalar, betul?', 'Sayur pakis dan rebung sering dimakan?', 'Daging rusa atau babi bakar, mana yang lebih sering?', 'Bubur sagu dan ikan kecil dari sungai juga?', 'Apa makanan khas dalam pesta panen ubi?'],
        tarian: ['Tari Tumbu Tanah untuk ritual pertanian, ceritanya?', 'Tari Pesta Ubi untuk syukuran panen, kapan dilaksanakan?', 'Apakah suku Amungme punya tari perang?', 'Gerakan Tari Tumbu Tanah seperti apa?', 'Apa nama tarian yang diiringi alat musik kecapi bambu?'],
        hari_besar: ['Upacara Tikim untuk inisiasi anak laki-laki, prosesnya gimana?', 'Pesta panen ubi diadakan bulan September sampai Oktober?', 'Apakah suku Amungme juga merayakan Festival Lembah Baliem?', 'Apa saja yang dilakukan dalam upacara Tikim?', 'Apakah ada hari besar khusus untuk perempuan Amungme?'],
        alat_musik: ['Alat musik suku Amungme: tifa kayu, fu suling bambu, dan kecapi bambu?', 'Kecapi bambu itu dipetik, bunyinya seperti apa?', 'Apakah tifa Amungme punya ukiran khusus?', 'Alat musik apa yang paling sakral bagi suku Amungme?', 'Perbedaan fu Amungme dengan fu Asmat?']
    },
    kamoro: {
        rumah_adat: ['Rumah adat suku Kamoro namanya Komea, bentuk panggung persegi panjang?', 'Komea dihuni 5–6 KK, lebih kecil dari Jew Asmat?', 'Bahan dari kayu dan atap sagu, tahan 10–15 tahun?', 'Fungsi Komea untuk tempat tinggal dan upacara, iya?', 'Di mana biasanya letak rumah Komea? Dekat pantai atau sungai?'],
        pakaian_laki_laki: ['Pria Kamoro memakai Kawatka, penutup kemaluan dari kayu atau labu?', 'Rok dari serat sagu, apakah mirip dengan Asmat?', 'Hiasan bulu kasuari dan cangkang kerang, biasanya dipakai di mana?', 'Apa beda Kawatka dengan koteka?', 'Apakah pria Kamoro juga memakai noken?'],
        pakaian_perempuan: ['Rok pendek wanita Kamoro dari serat sagu, betul?', 'Tubuh perempuan Kamoro bertato motif lingkaran dan garis, iya?', 'Kalung dari gigi anjing, apakah masih umum?', 'Apakah wanita Kamoro juga memakai penutup dada?', 'Tato Kamoro punya makna khusus?'],
        makanan: ['Makanan khas Kamoro: papeda, sagu bakar, ikan asap, betul?', 'Kepiting bakau dan udang sungai jadi makanan favorit?', 'Ulat sagu juga dimakan suku Kamoro?', 'Apa perbedaan papeda Kamoro dengan papeda Asmat?', 'Ada sayur atau umbi-umbian khas Kamoro?'],
        tarian: ['Tari topeng Kamoro namanya Tari Emakwe, untuk upacara apa?', 'Tari Mboti adalah tari gembira pasca panen, setiap 5 tahun sekali?', 'Apa makna topeng dalam Tari Emakwe?', 'Apakah ada tari perang di suku Kamoro?', 'Kapan biasanya Tari Mboti digelar?'],
        hari_besar: ['Upacara Mboti itu pesta sagu setiap 5 tahun sekali, benar?', 'Festival Kamoro diadakan setiap tahun, bulan apa?', 'Apa perbedaan Mboti dengan pesta panen suku lain?', 'Dalam upacara Mboti, apa saja yang dilakukan?', 'Apakah suku Kamoro punya upacara inisiasi seperti Tikim?'],
        alat_musik: ['Tifa ukir khas Kamoro, ukirannya motif apa?', 'Fu suling bambu dan Okobere terompet keong, itu alat musik tiup?', 'Apa alat musik Kamoro yang paling unik?', 'Apakah tifa Kamoro lebih panjang dari tifa Asmat?', 'Okobere biasanya dipakai untuk mengiringi tari apa?']
    },
    biak: {
        rumah_adat: ['Rumah adat suku Biak namanya Rumsram, bentuknya seperti perahu terbalik, iya?', 'Rumsram terbuat dari kayu besi dan atap rumbia, tahan 20–30 tahun?', 'Rumsram dihuni 2–3 keluarga, apakah satu rumpun keluarga besar?', 'Fungsi Rumsram selain tempat tinggal? Ada upacara naik rumah baru?', 'Apa keunikan Rumsram dibanding rumah adat Papua lainnya?'],
        pakaian_laki_laki: ['Pria Biak memakai Sali, yaitu kain cawat, benar?', 'Topi dari bulu cenderawasih, dan perisai dari kayu?', 'Gelang dan kalung dari kerang, apakah sebagai simbol status?', 'Apakah Sali sama dengan koteka? Beda, kan?', 'Aksesoris pria Biak yang paling mencolok apa?'],
        pakaian_perempuan: ['Wanita Biak memakai Sali pendek dari kulit kayu atau serat?', 'Rok rumbai dan mahkota dari bulu serta manik-manik?', 'Apakah wanita Biak juga memakai noken?', 'Perbedaan pakaian wanita Biak dengan Sentani?', 'Apakah wanita Biak bertato?'],
        makanan: ['Makanan khas Biak: papeda, ikan kuah kuning (tongkol), sagu lempeng?', 'Sagu lempeng itu sagu panggang seperti kue?', 'Kelapa muda sering dimakan bersama ikan?', 'Apakah suku Biak juga makan babi bakar?', 'Apa makanan tradisional untuk pesta laut?'],
        tarian: ['Tari Yospan perpaduan tari perang dan gembira, dari Biak?', 'Tari War itu tari perang, gerakannya agresif?', 'Apakah Tari Yospan masih sering dipentaskan?', 'Kapan biasanya Tari War ditarikan?', 'Apa nama tarian penyambutan tamu suku Biak?'],
        hari_besar: ['Festival Pesisir Biak diadakan bulan Juni–Juli, iya?', 'Upacara Naik Rumah Baru (Rumsram) seperti apa?', 'Pesta laut di Biak biasanya ada lomba perahu?', 'Apakah suku Biak merayakan upacara panen?', 'Apa makna Festival Pesisir Biak?'],
        alat_musik: ['Tifa Biak bentuknya lebih panjang dari tifa lain, benar?', 'Suling bambu, Mambisan (bambu dipukul), dan Gong kayu?', 'Mambisan dimainkan dengan cara dipukul, bunyinya seperti apa?', 'Apakah Tifa Biak punya ukiran khas?', 'Alat musik apa yang wajib ada dalam Tari Yospan?']
    },
    sentani: {
        rumah_adat: ['Rumah adat suku Sentani namanya Khouw, rumah panggung di atas danau atau daratan?', 'Bahan kayu besi dan atap ijuk, tahan 20 tahun?', 'Khouw dihuni 1 keluarga besar (3–4 KK), benar?', 'Apa fungsi Khouw selain tempat tinggal?', 'Apakah rumah Khouw memiliki anjungan khusus untuk memancing?'],
        pakaian_laki_laki: ['Pria Sentani memakai cawat dari kulit kayu, iya?', 'Hiasan kepala dari bulu cenderawasih, kalung manik-manik dan kerang?', 'Perisai kayu ukir, motifnya seperti apa?', 'Apakah pria Sentani memakai koteka? Tidak, kan?', 'Aksesoris yang paling bernilai bagi pria Sentani?'],
        pakaian_perempuan: ['Rok rumbai wanita Sentani dari serat sagu atau daun keladi?', 'Penutup dada dan noken, serta perhiasan manik-manik warna-warni?', 'Apakah wanita Sentani juga memakai mahkota bulu?', 'Perbedaan noken Sentani dengan noken Dani?', 'Apa bahan pewarna manik-manik tradisional Sentani?'],
        makanan: ['Makanan khas Sentani: ikan bakar dan goreng dari Danau Sentani?', 'Papeda sagu, umbi-umbian, sayur keladi, sagu lempeng?', 'Ikan apa yang paling terkenal dari Danau Sentani?', 'Apakah ada olahan sagu yang berbeda dengan papeda?', 'Sayur keladi dimasak dengan santan atau tidak?'],
        tarian: ['Tari Isosolo adalah tari selamat datang di atas air, gerakannya seperti apa?', 'Tari Ehabla adalah tari perang di panggung, iya?', 'Apakah Tari Isosolo dibawakan di atas perahu?', 'Kapan biasanya Tari Ehabla ditampilkan?', 'Apa nama tarian untuk menyambut Festival Danau Sentani?'],
        hari_besar: ['Festival Danau Sentani digelar bulan Juni–Juli, benar?', 'Ada lomba perahu hias dalam festival itu?', 'Upacara Mbate adalah syukuran ikan, prosesinya gimana?', 'Apa saja rangkaian acara Festival Danau Sentani?', 'Apakah suku Sentani juga punya upacara inisiasi?'],
        alat_musik: ['Alat musik Sentani: tifa kecil, fu suling bambu, kase, totobuang?', 'Kase itu alat musik tiup dari bambu, bunyinya seperti apa?', 'Totobuang adalah gong kecil dari kayu, bagaimana cara memainkannya?', 'Apakah tifa Sentani berbeda dengan tifa Biak?', 'Alat musik apa yang sering mengiringi Tari Isosolo?']
    }
};
